### ISSUE TITLE
Interested in Sharing with an Active Repo?

### ISSUE THREAD

**Issue by jrg94** [toturkmen/baklava#10]
Hey! You're Baklava project is awesome. I've never actually seen this style of problem.

Would you be interested in sharing your solutions with an active repo? I currently run [Sample Programs](https://github.com/jrg94/sample-programs) which is a collection of program snippets like this in every language. Currently, we support five snippets:

- Hello World
- Reverse a String
- Fizz Buzz
- Quine
- Game of Life

In total, we have support for about 80 languages, and we have over 100 snippets already collected. We'd love to add you baklava code to the collection. Let me know!

**Comment by toturkmen** [comment]
Hello! Yes, you can. 👍 Thank you for your interest.
